"""add company table

Revision ID: eb0b5f48f903
Revises: 2c3b2ee136dc
Create Date: 2025-11-12 22:38:58.962581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0b5f48f903'
down_revision: Union[str, None] = '2c3b2ee136dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.add_column('permission', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('role_permission', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key('fk_user_company_id_company', 'user', 'company', ['company_id'], ['id'])
    op.add_column('user_role', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'deleted_at')
    op.drop_constraint('fk_user_company_id_company', 'user', type_='foreignkey')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'company_id')
    op.drop_column('role_permission', 'deleted_at')
    op.drop_column('role', 'deleted_at')
    op.drop_column('permission', 'deleted_at')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
