/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPermissionToRoleTable: typeof import('./components/AddPermissionToRoleTable.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavigationBar: typeof import('./components/AppNavigationBar.vue')['default']
    copy: typeof import('./components/PermissionTable copy.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Permissions: typeof import('./components/tables/Permissions.vue')['default']
    PermissionTable: typeof import('./components/PermissionTable.vue')['default']
    RoleTable: typeof import('./components/RoleTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
  }
}
