/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPermissionToRoleTable: typeof import('./components/roles/AddPermissionToRoleTable.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavigationBar: typeof import('./components/AppNavigationBar.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    PermissionForm: typeof import('./components/permissions/PermissionForm.vue')['default']
    PermissionTable: typeof import('./components/permissions/PermissionTable.vue')['default']
    RoleForm: typeof import('./components/roles/RoleForm.vue')['default']
    RoleTable: typeof import('./components/roles/RoleTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
  }
}
